<?php

namespace ContainerSwQqSgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UyoORM4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uyoORM4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uyoORM4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.uyoORM4.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.uyoORM4": it references class "App\\Entity\\Client" but no such service exists.'],
            'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'factureRepository' => 'App\\Repository\\FactureRepository',
        ]);
    }
}
