<?php

namespace ContainerSwQqSgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OudDg7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OudDg7h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OudDg7h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'typeFactureRepository' => ['privates', 'App\\Repository\\TypeFactureRepository', 'getTypeFactureRepositoryService', true],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'typeFactureRepository' => 'App\\Repository\\TypeFactureRepository',
        ]);
    }
}
