<?php

namespace ContainerRxtddJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FC0DlFtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FC0DlFt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FC0DlFt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ligneFacture' => ['privates', '.errored..service_locator.FC0DlFt.App\\Entity\\LigneFacture', NULL, 'Cannot autowire service ".service_locator.FC0DlFt": it references class "App\\Entity\\LigneFacture" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'ligneFacture' => 'App\\Entity\\LigneFacture',
        ]);
    }
}
