<?php

namespace ContainerRxtddJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SehjztNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sehjztN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sehjztN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligneFacture' => ['privates', '.errored..service_locator.sehjztN.App\\Entity\\LigneFacture', NULL, 'Cannot autowire service ".service_locator.sehjztN": it references class "App\\Entity\\LigneFacture" but no such service exists.'],
        ], [
            'ligneFacture' => 'App\\Entity\\LigneFacture',
        ]);
    }
}
