<?php

namespace ContainerRxtddJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5MQ_FQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5MQ.fQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5MQ.fQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'facture' => ['privates', '.errored..service_locator.5MQ.fQH.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.5MQ.fQH": it references class "App\\Entity\\Facture" but no such service exists.'],
            'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService', true],
            'ligneFactureRepository' => ['privates', 'App\\Repository\\LigneFactureRepository', 'getLigneFactureRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'typeFactureRepository' => ['privates', 'App\\Repository\\TypeFactureRepository', 'getTypeFactureRepositoryService', true],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'facture' => 'App\\Entity\\Facture',
            'factureRepository' => 'App\\Repository\\FactureRepository',
            'ligneFactureRepository' => 'App\\Repository\\LigneFactureRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'typeFactureRepository' => 'App\\Repository\\TypeFactureRepository',
        ]);
    }
}
