<?php

namespace ContainerRxtddJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SrbsFukService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.srbsFuk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.srbsFuk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'service' => ['privates', '.errored..service_locator.srbsFuk.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.srbsFuk": it references class "App\\Entity\\Service" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'service' => 'App\\Entity\\Service',
        ]);
    }
}
