<?php

namespace ContainerRxtddJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ThTWmp8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ThTWmp8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ThTWmp8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'facture' => ['privates', '.errored..service_locator.ThTWmp8.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.ThTWmp8": it references class "App\\Entity\\Facture" but no such service exists.'],
            'ligneFactureRepository' => ['privates', 'App\\Repository\\LigneFactureRepository', 'getLigneFactureRepositoryService', true],
        ], [
            'facture' => 'App\\Entity\\Facture',
            'ligneFactureRepository' => 'App\\Repository\\LigneFactureRepository',
        ]);
    }
}
