<?php

namespace ContainerRxtddJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneFactureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FC0DlFt.App\Entity\LigneFacture' shared service.
     *
     * @return \App\Entity\LigneFacture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FC0DlFt": it references class "App\\Entity\\LigneFacture" but no such service exists.');
    }
}
