<?php

namespace Container3mYT4WQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8rbVmZ5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8rbVmZ5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8rbVmZ5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.8rbVmZ5.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.8rbVmZ5": it references class "App\\Entity\\Client" but no such service exists.'],
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'factureRepository' => 'App\\Repository\\FactureRepository',
        ]);
    }
}
