<?php

namespace Container3mYT4WQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O59BnH_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o59BnH.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o59BnH.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'facture' => ['privates', '.errored..service_locator.o59BnH..App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.o59BnH.": it references class "App\\Entity\\Facture" but no such service exists.'],
            'ligneFactureRepository' => ['privates', 'App\\Repository\\LigneFactureRepository', 'getLigneFactureRepositoryService', true],
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'facture' => 'App\\Entity\\Facture',
            'ligneFactureRepository' => 'App\\Repository\\LigneFactureRepository',
            'pdfService' => 'App\\Service\\PdfService',
        ]);
    }
}
