<?php

namespace Container3mYT4WQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UbH1RoHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ubH1RoH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ubH1RoH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'facture' => ['privates', '.errored..service_locator.ubH1RoH.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.ubH1RoH": it references class "App\\Entity\\Facture" but no such service exists.'],
            'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService', true],
        ], [
            'facture' => 'App\\Entity\\Facture',
            'factureRepository' => 'App\\Repository\\FactureRepository',
        ]);
    }
}
