<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3mYT4WQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3mYT4WQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3mYT4WQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3mYT4WQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3mYT4WQ\App_KernelDevDebugContainer([
    'container.build_hash' => '3mYT4WQ',
    'container.build_id' => '276c0ccb',
    'container.build_time' => 1700927089,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3mYT4WQ');
