<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSwQqSgH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSwQqSgH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSwQqSgH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSwQqSgH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSwQqSgH\App_KernelDevDebugContainer([
    'container.build_hash' => 'SwQqSgH',
    'container.build_id' => '27000b06',
    'container.build_time' => 1700566626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSwQqSgH');
